name: Docker Image CI

on:
  workflow_dispatch:


jobs:
  docker:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: generating tags
        id: tags
        uses: anothrNick/github-tag-action@1.40.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
   
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: toshibrat/my-images
          tags: ${{ steps.tags.outputs.tag }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
