name: Docker Image CI

on:
  workflow_dispatch:


jobs:
  docker:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker Login
        run : docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: BUild
        run: docker build .
