name: Docker Image CI

on:
  workflow_dispatch:


jobs:
  docker:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
   
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: toshibrat/my-images
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
